steps:
- name: gcr.io/cloud-builders/docker
  args: [
    "build",
    "-t", "gcr.io/$PROJECT_ID/$_REPO_NAME:$_TAG_NAME",
    "-f", "Dockerfile",
    ".",
  ]

substitutions:
  _REPO_NAME: triage-party
  _TAG_NAME: latest

images:
- 'gcr.io/$PROJECT_ID/$_REPO_NAME:$_TAG_NAME'
