# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

settings:
  name: minikube
  min_similarity: 0.72
  repos:
    - https://github.com/kubernetes/minikube

  member-roles:
    # Automatically add members from these roles (exclude default of "member")
    # See https://developer.github.com/v4/enum/commentauthorassociation/
    - collaborator
    - owner
  members:
    # Always consider these folks to be members
    - afbjorklund
    - josedonizetti
    - medyagh
    - priyawadhwa
    - sharifelgamal
    - tstromberg

collections:
  - id: daily-triage
    name: Daily Triage
    dedup: true
    description: >
      triage-onduty zeroes out this queue once a day. Prioritize:

       * Keeping an open dialog with our users
       * Initial prioritization (does not have to be perfect)
    rules:
      # SLO violations
      - issue-needs-priority-slo
      - issue-needs-comment-slo
      - issue-soon-slo
      - issue-longterm-slo
      # Don't leave code reviews hanging
      - pr-reviewable
      # missing initial feedback
      - issue-needs-kind
      - issue-needs-priority
      - issue-needs-comment
      # reprioritize
      - issue-new-with-reactions
      - issue-new-with-many-commenters
      # Don't forget our users
      - issue-updated-needs-info
      - issue-updated-has-question

  - id: weekly
    name: Weekly Triage
    dedup: true
    description: >
      Once a week, we meet up to address loose ends. Prioritize:

       * Keeping an open dialog with our users
       * Raising the priority for hot issues        
    rules:
      # SLO
      - issue-near-soon-slo
      - issue-near-longterm-slo
      # Issues needing reprioritization
      - many-reactions
      - many-commenters
      - issue-zombies
      # Issues needing closure
      - issue-stale-needs-info
      - issue-stale-support
      - lifecycle-rotten
      # PR's needing closure
      - pr-approved-stale
      - pr-unapproved-stale
      # People with questions
      - issue-has-question
      - issue-updated-support

  - id: scrub
    name: Bi-Monthly Scrub
    dedup: true
    description: >
      Once every two months, we look for stale issues and de-duplicate. Prioritize:

       * De-duplication
       * Keeping the bug queue relevant
       * Making tough decisions about long-standing requests
    rules:
      - lifecycle-stale
      - features-recv
      - features-old
      - bugs-recv
      - bugs-old
      - other-recv
      - other-old

  - id: milestone
    name: Next Milestone
    description: Items on the next milestone
    rules:
      - milestone-prs
      - milestone-features
      - milestone-bugs
      - milestone-other

  - id: tests
    name: Broken tests
    description: Failing tests, flaky tests, and other improvements
    rules:
      - failing-tests
      - flaky-tests
      - other-testing

  - id: similar
    name: Similar
    description: Items which appear similar to one other. Review for duplicates or vague titles.
    rules:
      - similar-prs
      - similar-issues

  - id: open
    name: All open PR's and Issues that should be considered for repository stats (hidden)
    used_for_statistics: true
    hidden: true
    rules:
      - open-prs
      - open-issues

rules:
  ### Daily Triage ####
  # SLO violations
  issue-needs-priority-slo:
    name: "Unprioritized issues older than 5 days"
    resolution: "Add a priority/ or triage/ label"
    type: issue
    filters:
      - label: "!priority/.*"
      - label: "!triage/.*"
      - created: +5d

  issue-needs-comment-slo:
    name: "Uncommented older than 5 days"
    resolution: "Add a comment"
    type: issue
    filters:
      - tag: "!commented"
      - tag: "recv"
      - created: +5d

  issue-soon-slo:
    name: "Important soon, but no updates in 60 days -- exceeds limit"
    resolution: "Downgrade to important-longterm"
    type: issue
    filters:
      - label: "priority/important-soon"
      - updated: +60d

  issue-longterm-slo:
    name: "Important longterm, but no updates in 120 days -- exceeds limit"
    resolution: "Downgrade to backlog"
    type: issue
    filters:
      - label: "priority/important-longterm"
      - updated: +120d

  # Don't leave code reviews hanging
  pr-reviewable:
    name: "Pull Requests: Review Ready"
    resolution: "Review requests or mark them as do-not-merge/work-in-progress"
    type: pull_request
    filters:
      - label: "!do-not-merge.*"
      - label: "!needs-rebase"
      - label: "!cncf-cla: no"
      - tag: "!requested-changes"
      - tag: "!send"
      # Temporarily workaround inability to track PR eligibility
      - updated: +1d

  # Issues missing initial feedback
  issue-needs-kind:
    name: "Unkinded Issues"
    resolution: "Add a kind/ or triage/support label"
    type: issue
    filters:
      - label: "!kind/.*"
      - label: "!triage/support"

  issue-needs-priority:
    name: "Unprioritized Issues within SLO"
    resolution: "Add a priority/ or triage/ label"
    type: issue
    filters:
      - label: "!priority/.*"
      - label: "!triage/.*"
      # avoid duplicating unkinded issues
      - label: "triage|kind"
      - created: -5d

  issue-needs-comment:
    name: "Uncommented Issues within SLO"
    resolution: "Add a comment"
    type: issue
    filters:
      - tag: "!commented"
      - tag: "recv"
      - created: -5d

  # Issues that may need reprioritized
  issue-new-with-reactions:
    name: "New, has multiple reactions, but not important-soon"
    resolution: "Check if issue should be prioritized as important-soon"
    type: issue
    filters:
      - reactions: ">2"
      - created: -10d
      - tag: "!send"
      - label: "!priority/important-soon"

  issue-new-with-many-commenters:
    name: "New, has multiple commenters, but not important-soon"
    resolution: "Check if issue should be prioritized as important-soon"
    type: issue
    filters:
      - commenters: ">3"
      - created: -10d
      - tag: "!send"
      - label: "!priority/important-soon"

  # Don't forget our users
  issue-updated-needs-info:
    name: "needs information, has update"
    resolution: "Comment and remove triage/needs-information tag"
    type: issue
    filters:
      - label: triage/needs-information
      - tag: recv

  issue-updated-has-question:
      name: "Recently updated issue has a question"
      resolution: "Add an answer"
      type: issue
      filters:
        - tag: recv-q
        - label: "!triage/needs-information"
        - tag: "!member-last"
        - tag: "!contributor-last"
        - responded: +3d
        - updated: -7d

  ####### Weekly Triage #########
  # SLO nearing
  issue-near-soon-slo:
    name: "Important soon, but no updates in 40 days -- nearing limit"
    resolution: "Downgrade to important-longterm"
    type: issue
    filters:
      - label: "priority/important-soon"
      - updated: +40d

  issue-near-longterm-slo:
    name: "Important longterm, but no updates in 110 days -- nearing limit"
    resolution: "Downgrade to backlog"
    type: issue
    filters:
      - label: "priority/important-longterm"
      - updated: +110d

  # issues needing reprioritization
  many-reactions:
    name: "many reactions, low priority"
    resolution: "Upgrade to priority-soon, priority-longterm, or longterm-support"
    filters:
      - reactions: ">3"
      - reactions-per-month: ">0.75"
      - label: "!priority/important-soon"
      - label: "!priority/important-longterm"
      - label: "!long-term-support"

  many-commenters:
    name: "many commenters, low priority"
    resolution: "Upgrade to priority-soon, priority-longterm, or longterm-support"
    filters:
      - commenters: ">2"
      - commenters-per-month: ">1.9"
      - created: "+30d"
      - label: "!priority/important-soon"
      - label: "!priority/important-longterm"
      - label: "!long-term-support"

  issue-zombies:
    name: "Screaming into the void"
    resolution: "Reopen, or ask folks to open a new issue"
    type: issue
    filters:
      - state: closed
      - updated: -7d
      - tag: recv
      - comments-while-closed: ">1"

  # Issues needing closure
  issue-stale-needs-info:
    name: "Needs information for over 2 weeks"
    resolution: "Close or remove triage/needs-information label"
    type: issue
    filters:
      - label: triage/needs-information
      - updated: +13d

  issue-stale-support:
    name: "Support request over 30 days old"
    resolution: "Close, or add to triage/long-term-support"
    type: issue
    filters:
      - label: triage/support
      - label: "!long-term-support"
      - updated: +29d

  lifecycle-rotten:
    name: "Issues nearing expiration"
    resolution: "Close or label as frozen"
    filters:
      - label: lifecycle/rotten

  # PR's needing closure
  pr-approved-stale:
    name: "Pull requests: Approved and getting old"
    type: pull_request
    filters:
      - label: "!do-not-merge.*"
      - label: "!needs-rebase"
      - label: "approved"
      - updated: +5d

  pr-unapproved-stale:
    name: "Pull Requests: Stale"
    resolution: "Add comment and/or close PR"
    type: pull_request
    filters:
      - created: +20d
      - updated: +5d
  
  # People with questions
  issue-has-question:
    name: "Overdue answers for a question"
    resolution: "Add a comment"
    type: issue
    filters:
      - tag: recv-q
      - label: "!triage/needs-information"
      - tag: "!member-last"
      - tag: "!contributor-last"
      - responded: +6d

  issue-updated-support:
    name: "Updated support requests"
    resolution: "Move out of support, or add a comment"
    type: issue
    filters:
      - tag: recv
      - label: "!triage/needs-information"
      - tag: "!member-last"
      - tag: "!contributor-last"
      - responded: +6d

  ## Bug Scrub ##
  bugs-recv:
    name: "Bugs that deserve a follow-up comment"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - tag: recv
      - responded: +45d
      - created: +45d
      - label: "kind/bug"

  features-recv:
    name: "Features that deserve a follow-up comment"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - tag: recv
      - responded: +60d
      - created: +30d
      - label: "kind/feature"

  other-recv:
    name: "Items that deserve a follow-up comment"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - tag: recv
      - responded: +30d
      - label: "!kind/feature"
      - label: "!kind/bug"
      - label: "!triage/support"

  features-old:
    name: "Features that have not been commented on within 90 days"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - responded: +90d
      - created: +90d
      - label: "kind/feature"

  bugs-old:
    name: "Bugs that have not been commented on within 60 days"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - label: "kind/bug"
      - responded: +60d
      - created: +60d
      - label: "!priority/awaiting-evidence"

  other-old:
    name: "Items that have not been commented on within 60 days"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - responded: +60d
      - created: +60d
      - label: "!kind/feature"
      - label: "!kind/bug"
      - label: "!triage/support"
      - label: "!priority/awaiting-evidence"

  lifecycle-stale:
    name: "Issues nearing expiration"
    resolution: "Close or label as frozen"
    filters:
      - label: lifecycle/stale

  # Milestone
  milestone-features:
    name: "v1.11.0 Features"
    type: issue
    resolution: Close em
    filters:
      - milestone: "v1.11.0 May28"
      - label: "kind/feature"

  milestone-bugs:
    name: "v1.11.0 Bugs"
    type: issue
    resolution: Close em
    filters:
      - milestone: "v1.11.0 May28"
      - label: kind/bug

  milestone-other:
    name: "v1.11.0 Other"
    type: issue
    resolution: Close em
    filters:
      - milestone: "v1.11.0 May28"
      - label: "!kind/feature"
      - label: "!kind/bug"

  milestone-prs:
    name: "v1.11.0 Pull Requests"
    type: pull_request
    resolution: Close em
    filters:
      - milestone: "v1.11.0 May28"

  ## Similar
  similar-prs:
    name: "Similar Pull Requests"
    type: pull_request
    resolution: Close as duplicate or give a better title
    filters:
      - tag: similar

  similar-issues:
    name: "Similar Issues"
    type: issue
    resolution: Close as duplicate or give a better title
    filters:
      - tag: similar

  ## Tests
  failing-tests:
    name: "Tests that fail 100% of the time"
    resolution: "Research and resolve"
    type: issue
    filters:
      - label: "kind/failing-test"

  flaky-tests:
    name: "Tests that fail some of the time"
    resolution: "Research and resolve"
    type: issue
    filters:
      - label: "kind/flake"
      - label: "!kind/failing-test"

  other-testing:
    name: "Other testing related issues"
    resolution: "Research and resolve"
    type: issue
    filters:
      - label: "area/testing"
      - label: "!kind/flake"
      - label: "!kind/failing"

  # for stastistics generation
  open-issues:
    name: "Open Issues"
    type: issue

  open-prs:
    name: "Open PRs"
    type: pull_request
