# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

settings:
  name: minimal

collections:
  - id: home
    name: Home
    rules:
      - issue-needs-comment
      - needs-review

rules:
  issue-needs-comment:
    name: "Unresponded, older than 3 days"
    type: issue
    filters:
      - tag: "!commented"
      - tag: "recv"
      - created: +3d

  needs-review:
    name: "Needs Review"
    type: pull_request
    filters:
      - title: "!.*(WIP|wip).*"
      - tag: "!draft"
      - tag: "(new-commits|unreviewed)"
