apiVersion: v1
kind: Service
metadata:
  name: triage-party
  namespace: triage-party
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 32080
    protocol: TCP
  selector:
    app: triage-party
