---
name: CI Build
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  docker:
    name: "Build app"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v2

      - name: Build image
        run: docker build --tag=tp .
